# Build Jekyll with preinstalled deps + add Pagefind index, then deploy to GitHub Pages
name: Deploy Jekyll with Pagefind

on:
  push:
    branches: ["main"]      # если основная ветка другая — поменяй
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Готовит окружение Pages и указывает, куда складывать сборку
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Сборка Jekyll в ./_site (официальный экшен GitHub)
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./           # корень репозитория
          destination: ./_site # выходная папка

      # Доставляем Pagefind прямо в _site
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Pagefind index
        run: |
          npm i -g pagefind@latest
          # Собираем индекс по готовому сайту (_site) и кладём UI-файлы в _site/pagefind
          # Комментарии оставляем в индексе, язык форсим на ru, чтобы не ругался на lang
          pagefind --site _site --force-language ru

      # Загружаем артефакт (по умолчанию возьмёт _site из configure-pages)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
